### ISSUE TITLE
Specifying MySQL Server Settings?

### ISSUE THREAD

**Issue by jonmchan** [jalkoby/squasher#40]
I'm getting:

```
Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/Users/jonathan/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/jonathan/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

I don't have sockets open, but use a TCP/IP connection. Is there a way to pass parameters to squasher? I use dotenv - is squasher not picking up the config from dotenv?

**Comment by jalkoby** [comment]
Hi. Squasher requires a valid database.yml config, so on time of squashing please add it and on finish just remove the config file

**Comment by jonmchan** [comment]
The issue is that my database.yml config file specifies ENV['DB_HOST'] variable that in development, is populated by the dotenv gem (https://github.com/bkeepers/dotenv). Squasher is loading up before .env not allowing the ENV['DB_HOST'] environment variable to be properly set. I had to manually load in the shell ```export DB_HOST='...'```. It is a simple enough workaround, but I think it is worth noting that there is a compatibility issue with dotenv and squasher.

**Comment by jalkoby** [comment]
yes, I understood your case from the first time - I'm sorry to say, but there are no plans to add such workarounds. The reason is simple - there are many of dotnet loaders (no common used solution) and I have to spend a lot of time to add each of them and then maintain. The cost is to high to the end result
